name: Dagster Cloud CI/CD
on:
  push:
    branches:
      - main

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # Set up Docker registry access
      # See https://github.com/docker/login-action for more examples

      # ECR
      ## https://github.com/aws-actions/amazon-ecr-login#usage
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # e.g. us-west-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      ## DockerHub
      ## https://github.com/docker/login-action#docker-hub
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      ## GitHub Container Registry
      ## https://github.com/docker/login-action#github-container-registry
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      ## GCR
      ## https://github.com/docker/login-action#google-container-registry-gcr
      # - name: Login to GCR
      #   uses: docker/login-action@v1
      #   with:
      #     registry: gcr.io
      #     username: _json_key
      #     password: ${{ secrets.GCR_JSON_KEY }}

      - name: Run Dagster Cloud CI/CD action
        uses: dagster-io/dagster-cloud-cicd-action/deploy@v0.2.4
        with:
          location-file: locations.yaml
          # Specify your Dagster Cloud Dagit organization, deployment, and token in the GitHub secrets page
          # e.g. organization: hooli, deployment: prod
          dagit-url: https://${{ secrets.DAGSTER_CLOUD_ORGANIZATION }}.dagster.cloud/${{ secrets.DAGSTER_CLOUD_DEPLOYMENT }}
          # e.g. agent:hooli:1193cb69aaa34cfz83d44adcfe89b057
          api-token: ${{ secrets.DAGSTER_CLOUD_AGENT_TOKEN }}